/**
 * MegaTrix Multi-SaaS Platform Registry
 * Configures all active and future SaaS products managed via MegaTrix Admin Core.
 * Enforces strict platform isolation: Users and subscriptions are scoped per platform.
 */
export const PLATFORMS = [
  {
    id: 'bizmanager',
    name: 'BizManager',
    code: 'BIZ',
    tagline: 'Retail POS & Grocery Billing ERP',
    description: 'Enterprise point of sale, inventory tracking, debtor khata, and cash/bank ledger management for retail stores.',
    apiUrl: import.meta.env.VITE_BIZMANAGER_API_URL || 'http://localhost:5000',
    appUrl: import.meta.env.VITE_BIZMANAGER_APP_URL || 'http://localhost:5173',
    color: 'emerald',
    badgeColor: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    status: 'active',
    version: 'v2.4.0',
    capabilities: {
      userManagement: true,
      subscriptionManagement: true,
      deviceTracking: true,
      posInvoicing: true,
      khataLedgers: true,
      instantBlock: true,
    },
    quickStats: {
      category: 'Retail & POS ERP',
      defaultTrialDays: 14,
      currency: 'PKR',
      accountType: 'Merchant / Store Owner',
    },
    subscriptionPlans: [
      { id: 'starter', name: 'Starter POS', price: 'PKR 2,500/mo', features: ['1 Terminal', 'Up to 500 SKUs', 'Basic Khata'] },
      { id: 'pro', name: 'Pro Enterprise', price: 'PKR 6,500/mo', features: ['Unlimited Terminals', 'Barcode Scanner', 'Bank & Loan Ledgers'] },
      { id: 'lifetime', name: 'Lifetime License', price: 'PKR 45,000 once', features: ['Permanent Access', 'All Features', 'Priority Support'] },
    ],
  },
  {
    id: 'schoolmanager',
    name: 'School Manager',
    code: 'SMS',
    tagline: 'Pakistani Institutional School ERP SaaS',
    description: 'Unified multi-tenant school operating system with 3-copy bank challans, student directories, timetable clash audit, and 4-role portals.',
    apiUrl: import.meta.env.VITE_SCHOOLMANAGER_API_URL || 'http://localhost:5001/api',
    appUrl: import.meta.env.VITE_SCHOOLMANAGER_APP_URL || 'http://localhost:5174',
    color: 'sky',
    badgeColor: 'bg-sky-500/10 text-sky-400 border-sky-500/20',
    status: 'active',
    version: 'v3.0.0 Pro',
    capabilities: {
      userManagement: true,
      subscriptionManagement: true,
      institutionalIsolation: true,
      threeCopyChallans: true,
      rolePortals: true, // Admin, Teacher, Staff, Parent
      timetableAudit: true,
    },
    quickStats: {
      category: 'Education SaaS',
      defaultTrialDays: 30,
      currency: 'PKR',
      accountType: 'Institutional School Code',
    },
    subscriptionPlans: [
      { id: 'campus_basic', name: 'Single Campus', price: 'PKR 12,000/mo', features: ['Up to 500 Students', '3-Copy Challans', 'Admin & Teacher Portals'] },
      { id: 'campus_pro', name: 'Multi-Branch Pro', price: 'PKR 25,000/mo', features: ['Up to 2,500 Students', 'Parent App', 'Staff HR & Payroll', 'SMS Gateway'] },
      { id: 'campus_enterprise', name: 'Group of Schools', price: 'PKR 55,000/mo', features: ['Unlimited Campuses', 'Centralized Accounts', 'Custom Branding'] },
    ],
  },
  {
    id: 'mailerx',
    name: 'MailerX Hub',
    code: 'MLX',
    tagline: 'Unified Email & Notification Engine',
    description: 'Centralized high-deliverability transactional email dispatcher, outbox queue monitor, and responsive template manager for all MegaTrix SaaS products.',
    apiUrl: '',
    appUrl: '',
    color: 'indigo',
    badgeColor: 'bg-indigo-500/10 text-indigo-400 border-indigo-500/20',
    status: 'active',
    version: 'v1.5.0 Core',
    capabilities: {
      userManagement: false,
      subscriptionManagement: false,
      smtpRelay: true,
      brevoIntegration: true,
      templateStudio: true,
      deliveryTelemetry: true,
    },
    quickStats: {
      category: 'Shared Platform Service',
      defaultTrialDays: 0,
      currency: 'USD',
      accountType: 'Service API Token',
    },
    subscriptionPlans: [
      { id: 'shared_tier', name: 'Global Platform Shared Tier', price: 'Included', features: ['Cross-SaaS Relay', 'Transactional OTPs', 'Challan Notifications'] },
    ],
  },
  {
    id: 'leadhunter',
    name: 'LeadHunter Pro',
    code: 'LHP',
    tagline: 'B2B Prospecting & Outreach Pipeline',
    description: 'High-velocity lead scraping, enrichment, and cold email automated sequencer for agency client acquisition.',
    apiUrl: import.meta.env.VITE_LEADHUNTER_API_URL || '',
    appUrl: '',
    color: 'amber',
    badgeColor: 'bg-amber-500/10 text-amber-400 border-amber-500/20',
    status: 'coming_soon',
    version: 'v0.9.0',
    capabilities: {
      userManagement: true,
      subscriptionManagement: true,
      enrichmentCredits: true,
    },
    quickStats: {
      category: 'Sales Tech',
      defaultTrialDays: 7,
      currency: 'USD',
      accountType: 'Agency / Marketer',
    },
    subscriptionPlans: [],
  },
  {
    id: 'mega-ai',
    name: 'Mega-AI Assistant',
    code: 'MAI',
    tagline: 'Autonomous Enterprise AI Workspace',
    description: 'Multi-model agentic workspace for document intelligence, automation, and analytics.',
    apiUrl: import.meta.env.VITE_MEGAAI_API_URL || '',
    appUrl: '',
    color: 'violet',
    badgeColor: 'bg-violet-500/10 text-violet-400 border-violet-500/20',
    status: 'coming_soon',
    version: 'v1.0.0-beta',
    capabilities: {
      userManagement: true,
      subscriptionManagement: true,
      deviceTracking: true,
      tokenUsage: true,
    },
    quickStats: {
      category: 'AI & Intelligence',
      defaultTrialDays: 7,
      currency: 'USD',
      accountType: 'Workspace Member',
    },
    subscriptionPlans: [],
  },
  {
    id: 'autoposting',
    name: 'AutoPosting MegaTrix',
    code: 'APM',
    tagline: 'Multi-Channel Social Automation Engine',
    description: 'Autonomous social media scheduling, analytics, and content generation suite.',
    apiUrl: import.meta.env.VITE_AUTOPOSTING_API_URL || '',
    appUrl: '',
    color: 'rose',
    badgeColor: 'bg-rose-500/10 text-rose-400 border-rose-500/20',
    status: 'coming_soon',
    version: 'v1.1.0',
    capabilities: {
      userManagement: true,
      subscriptionManagement: true,
      channelStats: true,
    },
    quickStats: {
      category: 'Marketing Tech',
      defaultTrialDays: 14,
      currency: 'USD',
      accountType: 'Creator / Brand',
    },
    subscriptionPlans: [],
  },
];

export const getDefaultPlatform = () => PLATFORMS[0];

export const getPlatformById = (id) => PLATFORMS.find((p) => p.id === id) || PLATFORMS[0];
